[providers.openrouter]
baseUrl = "https://openrouter.ai/api/v1"
authHeader = "Bearer"
keyEnvVar = "OPENROUTER_API_KEY"

[providers.vercel]
baseUrl = "https://ai-gateway.vercel.sh/v1"
authHeader = "Bearer"
keyEnvVar = "VERCEL_AI_KEY"

[providers.aihubmix]
baseUrl = "https://aihubmix.com/v1"
authHeader = "Bearer"
keyEnvVar = "AIHUBMIX_API_KEY"

[providers.deepseek]
baseUrl = "https://api.deepseek.com/v1"
authHeader = "Bearer"
keyEnvVar = "DEEPSEEK_API_KEY"

[models."openai/gpt-5.5"]

[[models."openai/gpt-5.5".providers]]
name = "openrouter"
remap = "openai/gpt-5.5"

[[models."openai/gpt-5.5".providers]]
name = "aihubmix"
remap = "gpt-5.5"

[[models."openai/gpt-5.5".providers]]
name = "vercel"
remap = "openai/gpt-5.5"

[models."anthropic/claude-opus-4.7"]

[[models."anthropic/claude-opus-4.7".providers]]
name = "openrouter"
remap = "anthropic/claude-opus-4.7"

[[models."anthropic/claude-opus-4.7".providers]]
name = "aihubmix"
remap = "claude-opus-4.7"
    
[[models."anthropic/claude-opus-4.7".providers]]
name = "vercel"
remap = "anthropic/claude-opus-4.7"

[models."google/gemini-3.1-pro-preview"]

[[models."google/gemini-3.1-pro-preview".providers]]
name = "openrouter"
remap = "google/gemini-3.1-pro-preview"

[[models."google/gemini-3.1-pro-preview".providers]]
name = "aihubmix"
remap = "gemini-3.1-pro-preview"

[[models."google/gemini-3.1-pro-preview".providers]]
name = "vercel"
remap = "google/gemini-3.1-pro-preview"

[models."deepseek/deepseek-v4-flash"]

[[models."deepseek/deepseek-v4-flash".providers]]
name = "deepseek"
remap = "deepseek-v4-flash"

[models."deepseek/deepseek-v4-pro"]

[[models."deepseek/deepseek-v4-pro".providers]]
name = "deepseek"
remap = "deepseek-v4-pro"
